name: Mark Trapp
tagline: Philosophical ideas in usability, technology, and management.
timezone: America/Los_Angeles
uri: http://marktrapp.com

source: jekyll
lsi: false

# Project permalinks use /projects/:category/:title and are set on each post.
permalink: /blog/:year/:month/:day/:title

encoding: UTF-8
markdown: redcarpet
pygments: false

archive:
    path: /blog
    layout: archive
    exclude: ['projects', 'hidden']

redcarpet:
    extensions: ['highlight', 'footnotes']

# Site-specific settings.
author:
    name: Mark Trapp
    uri: http://marktrapp.com
    email: mark@marktrapp.com
copyright: Copyright © Mark Trapp. All rights reserved.

diffprefix: https://github.com/itafroma/itafroma.github.io/commits/master/
googleanalytics:
    account: UA-767493-8
    domain: marktrapp.com
