name: Mark Trapp
tagline: Philosophical ideas in usability, technology, and management.
timezone: UTC
uri: http://marktrapp.com
domain: marktrapp.com

source: jekyll
lsi: false

# Project permalinks use /projects/:category/:title and are set on each post.
permalink: /blog/:year/:month/:day/:title

encoding: UTF-8
markdown: ItafromaRedcarpetExtra
highlighter: nil
gems:
    - 'jekyll/itafroma/archive'
    - 'jekyll/itafroma/collapse_newlines'
    - 'jekyll/itafroma/indent_filter'
    - 'jekyll/itafroma/post_groups'

archive:
    path: /blog
    layout: archive
    exclude: ['projects', 'hidden', 'pages']

post_groups:
    - key: section
      group: sections
    - key: layout
      group: post_groups

blog_presort: ['Programming', 'Philosophy']

redcarpet:
    extensions: ['highlight', 'footnotes']

defaults:
    - scope:
        path: ''
      values:
        layout: 'page'
    - scope:
        path: 'blog'
      values:
        layout: 'post'
    - scope:
        path: 'projects'
      values:
        layout: 'project'

author:
    name: Mark Trapp
    uri: http://marktrapp.com
    email: mark@marktrapp.com
    twitter: "@itafroma"
copyright: Copyright © Mark Trapp. All rights reserved.

cta: "Comments and feedback are welcome and appreciated. Need help on your next project? [Let's talk](/contact)."

feed:
    categories: ['blog', 'projects']

sourcecode: https://github.com/itafroma/marktrapp.com

prefix:
    diff: https://github.com/itafroma/marktrapp.com/commits/production/jekyll/
    edit: https://github.com/itafroma/marktrapp.com/edit/production/jekyll/
    file: http://files.marktrapp.com/

googleanalytics:
    account: UA-767493-8
    domain: marktrapp.com
